apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: openshift-storage
spec:
 dbResources:
   requests:
     cpu: '1'
     memory: 2Gi
 dbType: postgres
 coreResources:
   requests:
     cpu: '1'
     memory: 2Gi
