apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: lab-registry
  namespace: quay-enterprise
spec:
  components:
    - managed: true
      kind: clair
    - managed: true
      kind: postgres
    - managed: true
      kind: objectstorage
    - managed: true
      kind: redis
    - managed: false
      kind: horizontalpodautoscaler
    - managed: true
      kind: route
    - managed: false
      kind: mirror
    - managed: false
      kind: monitoring
    - managed: true
      kind: tls
    - overrides:
        replicas: 1
      managed: true
      kind: quay
    - managed: true
      kind: clairpostgres
